spring.application.name=student
spring.datasource.url=jdbc:mysql://localhost:3306/student_database
spring.datasource.username=root
spring.datasource.password=root

spring.data.redis.host=localhost
spring.data.redis.port=6379


